spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: none

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/fullstackhandyman
        username: #username
        password: #password